spring:
  profiles:
    active: dev
server:
  port: 8993
  servlet:
    session:
      timeout: 86400
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql