spring:
  datasource:
    url: jdbc:mysql://129.28.138.157:3663/dundun?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&zeroDateTimeBehavior=convertToNull
    username: root
    password: root<>JeffyLi123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.auto-commit: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.boot.autoconfigure: info